export const PREFIX = `CODE_SNIPPET_`;
export const EXAMPLE_LIST = `EXAMPLE_LIST`;

export const CODE_SNIPPET_REQUEST_FETCH_LIST = `${PREFIX}REQUEST_FETCH_LIST`;
export const CODE_SNIPPET_RECEIVE_FETCH_LIST = `${PREFIX}RECEIVE_FETCH_LIST`;

export const CODE_SNIPPET_REQUEST_CREATE = `${PREFIX}REQUEST_CREATE`;

export const CODE_SNIPPET_REQUEST_DELETE = `${PREFIX}REQUEST_DELETE`;
